### ISSUE TITLE
#UI/Groupchat mode : messages from creator and critic not visible

### ISSUE THREAD

**Issue by swappybizz** [bonadio/autogenwebdemo#1]
When in groupchatmode i.e,
`from autogen_group_chat import AutogenChat`
replaces
`from autogen_chat import AutogenChat`
in main.py
messages from creator and critiq not visible in UI

**Comment by bonadio** [comment]
The way it is implemented only messages to user_proxy shows in UI. If you want tho show the other agents messages in the UI you need to create a queue and pass to then, just follow the same pattern as the user_proxy does

**Comment by swappybizz** [comment]
tusen tak i  shall try
