### ISSUE TITLE
Use of WebSockets with RAG agent

### ISSUE THREAD

**Issue by gh0stlayer** [bonadio/autogenwebdemo#8]
Hi @bonadio, thanks for providing this repo.
I wanted some guidance on how can I apply this on RAG based chatbot. Bot will perform RAG on each input query and then provide response of the user.

I am using Autogen: https://github.com/microsoft/autogen/blob/main/notebook/agentchat_RetrieveChat.ipynb
For creating 2 agents one as RAG User Proxy and other RAG Assistant. 

I want to deploy pipeline into same manner as your repo. Any help from your end will be very great for me.

**Comment by bonadio** [comment]
Hi @swaroop11, I never tested the RAG agent. But I think it should work.
